// src/lib/ColorButton.svelte
<script lang="ts">
  import { launchpadColorToHexString, getTextColor, launchpadColorToString } from '../types/colors';
  import FloatingColorPicker from './FloatingColorPicker.svelte';
  import type { LaunchpadColor } from '../types/notes';

  export let value: LaunchpadColor;
  export let index: number;
  export let onChange: (value: LaunchpadColor) => void;

  let showPicker = false;
  let pickerStyle = {
    position: 'fixed',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    zIndex: '1000'
  };
</script>

<div class="color-button-container">
  <button
    class="color-preview"
    tabindex={index}
    style="background-color: {launchpadColorToHexString(value)}; color: {getTextColor(value)}"
    on:click={() => showPicker = true}
  >
    {launchpadColorToString(value)}
  </button>
  {#if showPicker}
    <FloatingColorPicker
      {value}
      onChange={(e) => {
        onChange(e);
        showPicker = false;
      }}
      onClose={() => showPicker = false}
      style={pickerStyle}
    />
  {/if}
</div>

<style>
  .color-button-container {
    display: inline-block;
  }

  .color-preview {
    width: 24px;
    height: 24px;
    border: 1px solid var(--border-color);
    border-radius: 4px;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    background-color: var(--bg-color);
    font-size: 12px;
  }

</style>

// src/components/ColorButton.tsx
import React, { useState } from 'react';
import { launchpadColorToHexString, getTextColor, launchpadColorToString } from '../types/colors';
import FloatingColorPicker from './FloatingColorPicker';
import { LaunchpadColor } from '../types/notes';

interface ColorButtonProps {
  value: LaunchpadColor;
  onChange: (value: LaunchpadColor) => void;
}

const ColorButton: React.FC<ColorButtonProps> = ({
  value,
  onChange
}) => {
  const [showPicker, setShowPicker] = useState(false);

  return (
    <div className="color-button-container">
      <div
        className="color-preview"
        style={{
          backgroundColor: launchpadColorToHexString(value),
          color: getTextColor(value)
        }}
        onClick={() => setShowPicker(true)}
      >
        {launchpadColorToString(value)}
      </div>
      {showPicker && (
        <FloatingColorPicker
          value={value}
          onChange={(newValue) => {
            onChange(newValue);
            setShowPicker(false);
          }}
          onClose={() => setShowPicker(false)}
          style={{
            position: 'fixed',
            top: '50%',
            left: '50%',
            transform: 'translate(-50%, -50%)',
            zIndex: 1000
          }}
        />
      )}
    </div>
  );
};

export default ColorButton;
