// src/lib/GridKeyboard.svelte
<script lang="ts">
  import { launchpadColorToHexString, getTextColor } from '../types/colors';
  import FloatingColorPicker from './FloatingColorPicker.svelte';
  import { type Note, type LaunchpadColor, type NoteMap, GRID_LAYOUT } from '../types/notes';
  import { shouldLightUp, type NoteState, type KeyState, type ShowSameNote } from '../types/ui';
  import NoteInput from './NoteInput.svelte';
  
  export let activeNotes: NoteState = {};
  export let activeKeys: KeyState = {};
  export let onKeyPress: (note: number) => void;
  export let onKeyRelease: (note: number) => void;
  export let noteMap: NoteMap;
  export let setNoteMap: (noteMap: NoteMap) => void;
  export let showSameNotePressed: ShowSameNote;

  const isActiveNote = (noteState: NoteState, note: number) => {
    return noteState[note] && noteState[note] > 0;
  };

  let colorPickerCell: Note | null = null;

  function handleNoteChange(src: Note, newNote: Note) {
    if (noteMap[src]) {
      const newNoteMap = {...noteMap};
      newNoteMap[src] = {
        ...newNoteMap[src],
        target: newNote
      };
      setNoteMap(newNoteMap);
    }
  }

  function getKeyColor(src: Note): LaunchpadColor {
    return shouldLightUp(noteMap[src].target, activeNotes, showSameNotePressed)
      ? noteMap[src].color.pressed 
      : noteMap[src].color.rest;
  }
</script>

<div class="grid-keyboard-container">
  <div class="grid-keyboard">
    <div class="grid-container">
      {#each GRID_LAYOUT.toReversed() as row}
        <div class="grid-row">
          {#each row as src}
            <div
              class="grid-cell {activeKeys[src] ? 'active' : ''}"
              style="background-color: {launchpadColorToHexString(getKeyColor(src))}"
              role="button"
              tabindex="0"
              on:mousedown={(e) => {
                if (!e.defaultPrevented) {
                  onKeyPress(src);
                }
              }}
              on:mouseup={() => onKeyRelease(src)}
              on:mouseleave={() => activeKeys[src] && onKeyRelease(src)}
              on:contextmenu|preventDefault={(e) => {
                e.stopPropagation();
                colorPickerCell = src;
              }}
            >
              <div class="cell-content">
                <NoteInput
                  id={`note-${src}`}
                  data={noteMap[src].target}
                  onChange={(newNote) => handleNoteChange(src, newNote)}
                  asButton={true}
                  className="note-name"
                  style="color: {getTextColor(getKeyColor(src))}"
                />
              </div>
            </div>
          {/each}
        </div>
      {/each}
    </div> 
  </div> 
</div>

<style>
  .grid-keyboard-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 100%;
    margin: 20px 0;
  }

  .grid-keyboard {
    display: flex;
    flex-direction: column;
    gap: 8px;
    padding: 24px;
    background-color: var(--grid-bg);
    border: 1px solid var(--border-color);
    border-radius: 12px;
    max-width: 600px;
    margin: 0 auto;
    box-shadow: 0 4px 12px var(--shadow-color);
  }

  .grid-container {
    display: flex;
    flex-direction: column;
    gap: 8px;
  }

  .grid-row {
    display: flex;
    gap: 8px;
    justify-content: center;
  }

  .grid-cell {
    width: 56px;
    height: 56px;
    border: none;
    border-radius: 8px;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    transition: all 0.15s ease;
    position: relative;
    user-select: none;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
  }

  .grid-cell:hover {
    transform: translateY(-1px);
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);
  }

  .grid-cell.active {
    transform: translateY(2px);
    box-shadow: 0 1px 2px rgba(0, 0, 0, 0.3);
  }

  .cell-content {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 4px;
  }
</style>

// src/components/GridKeyboard.tsx
import React, { useEffect, useState } from 'react';
import { isActiveNote, KeyState, NoteState } from '../types';
import { launchpadColorToHexString, getTextColor } from '../types/colors';
import FloatingColorPicker from './FloatingColorPicker';
import { stringToNote, Note, LaunchpadColor, NoteMap, noteToString, GRID_LAYOUT } from '../types/notes';

interface GridKeyboardProps {
  activeNotes: NoteState;
  activeKeys: KeyState;
  onKeyPress: (note: Note) => void;
  onKeyRelease: (note: Note) => void;
  noteMap: NoteMap;
  setNoteMap: (noteMap: NoteMap) => void;
  showSameNotePressed: boolean;
}

const GridKeyboard: React.FC<GridKeyboardProps> = ({ onKeyPress, onKeyRelease, setNoteMap, activeNotes, activeKeys, noteMap, showSameNotePressed }) => {
  const [editingCell, setEditingCell] = useState<Note | null>(null);
  const [editValue, setEditValue] = useState<string>('');
  const [colorPickerCell, setColorPickerCell] = useState<Note | null>(null);

  const handleEditSubmit = () => {
    if (editingCell) {
      const parsedNote = stringToNote(editValue);
      
      if (parsedNote !== null && noteMap[editingCell]) {
        const newNoteMap = {...noteMap};
        newNoteMap[editingCell] = {
          ...newNoteMap[editingCell],
          target: parsedNote
        };
        setNoteMap(newNoteMap);
      }
      setEditingCell(null);
      setEditValue('');
    }
  };

  const handleEditKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') {
      handleEditSubmit();
    } else if (e.key === 'Escape') {
      setEditingCell(null);
      setEditValue('');
    }
  };

  const handleEditStart = (src: Note) => {
    setEditingCell(src);
    setEditValue(noteToString(noteMap[src].target));
  };

  const handleColorChange = (colorCode: LaunchpadColor) => {
    if (colorPickerCell) {
      const mapping = noteMap[colorPickerCell];
      if (mapping) {
        const newnoteMap = {...noteMap};
        newnoteMap[colorPickerCell] = {
          ...newnoteMap[colorPickerCell],
          ['restColor']: colorCode
        };
        setNoteMap(newnoteMap);
        setColorPickerCell(null);
      }
    }
  };

  const noteComponent = React.useCallback((src: Note) => {
    let keyColor = activeKeys[src] || (showSameNotePressed && isActiveNote(activeNotes, noteMap[src].target))
                 ? noteMap[src].pressedColor 
                 : noteMap[src].restColor;
    return (<div
        key={`cell-${src}`}
        className={`grid-cell ${activeKeys[src] ? 'active' : ''}`}
        style={{
          backgroundColor: launchpadColorToHexString(keyColor) 
        }}
        onMouseDown={(e) => {
          if (!e.defaultPrevented) {
            onKeyPress(src);
          }
        }}
        onMouseUp={() => onKeyRelease(src)}
        onMouseLeave={() => activeKeys[src] && onKeyRelease(src)}
        onContextMenu={(e) => {
          e.preventDefault();
          e.stopPropagation();
          setColorPickerCell(src);
        }} >
        {editingCell === src ? (
          <input
            type="text"
            value={editValue}
            onChange={(e) => setEditValue(e.target.value)}
            onKeyDown={handleEditKeyDown}
            onBlur={handleEditSubmit}
            autoFocus
            onClick={(e) => e.stopPropagation()}
          />
        ) : (
          <div className="cell-content">
            <div 
              className="note-name" 
              style={{
                color: getTextColor(keyColor)
              }}
              onClick={(e) => {
                e.preventDefault();
                e.stopPropagation();
                handleEditStart(src);
              }}
            >{noteToString(noteMap[src].target)}</div>
          </div>
        )}
      </div>);
  }, [activeKeys, activeNotes, noteMap, showSameNotePressed]);

  return (
    <div className="grid-keyboard-container">
      <div className="grid-keyboard">
        <div className="grid-container">
          {GRID_LAYOUT.toReversed().map(row => (
            <div key={`row-${row}`} className="grid-row">{row.map(src => noteComponent(src))}</div>))}
        </div> 
      </div> 
      {colorPickerCell && (
        <FloatingColorPicker
          value={noteMap[colorPickerCell].restColor}
          onChange={handleColorChange}
          onClose={() => setColorPickerCell(null)}
          position="center"
        />
      )}
    </div>
  );
};

export default GridKeyboard;
